# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

stages:
    - deploy

deploy:
    stage: deploy
    script:
        - python -V  # Print out python version for debugging
        - pip install poetry
        - poetry config virtualenvs.create false
        - poetry install 
        - poetry publish --build -u $PYPI_UNAME -p $PYPI_PASS
