# This file is a template, and might need editing before it works on your project.
# Official language image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/python/tags/
image: python:latest

stages:
    - deploy

before_install:
    script:
        - python -V  # Print out python version for debugging
        - pip install poetry
        - poetry config virtualenvs.create false
        - poetry install 

#test:
#  script:
#    - python setup.py test
#    - pip install tox flake8  # you can also use tox
#    - tox -e py36,flake8


deploy:
    stage: deploy
    script:
        - poetry publish --build -u mexiquin -p $uperm@n$lipper$1A
